### PR TITLE
🐛 Fix DockerMachine delete for first control plane

### LINKED ISSUE #109: Final control plane node can never be deleted
/kind bug

**What steps did you take and what happened:**
1. Create a kind management cluster
2. create a capa cluster using capd
3. delete the capd cluster (using the changes in kubernetes-sigs/cluster-api#1180 so the machines get deleted first)
4. Control plane node fails to delete with an error like `failed with exit code one`

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The cluster will try to [find another control-plane node to run kubectl on](https://github.com/kubernetes-sigs/cluster-api-provider-docker/blob/master/kind/actions/cluster_actions.go#L307-L310), but of course no such container exists. It will therefore try to execute a command on a container with the name of the empty string, which doesn't exist.

**Environment:**

- Cluster-api-provider-docker version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**: This PR allows the deletion of the final/first control plane

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #109 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: docker/actions/kind.go [hunk 1]
```diff
@@ -155,27 +155,30 @@ func (m *MachineActions) DeleteControlPlane(clusterName, nodeName string) error
...
-	// pick the first one, but there should never be multiples since docker requires name to be unique.
 	node := nodeList[0]
-	if err := DeleteClusterNode(clusterName, nodeName); err != nil {
-		return err
-	}
-	if err := KubeadmReset(clusterName, nodeName); err != nil {
-		return err
+
+	// Only issue a KubeadmReset and corev1.Node delete if there are multiple nodes.
+	if len(nodeList) > 2 {
```
Comment (detiber) [inline docker/actions/kind.go]: Is this >2 because the lb is included? If so, can you add a comment?

**Comment by chuckha** [comment]
hmm I see what I've done and this is not right. Updating.

**Comment by chuckha** [comment]
@detiber updated. Much cleaner.
