### PR TITLE
All the fixes for cluster api v0.1.4

### LINKED ISSUE #32: Don't copy/paste the CRDs from Cluster API
It would be great to not copy and paste the CRDs from cluster API.

Ideally capdctl can produce the YAML from multiple versions of Cluster API. I propose a command that looks like this:

`capdctl crds <cluster-api-version>`

for example

`capdctl crds 0.1.3`

This will then print out the crds.

There are two implementations that come to mind: 1) capdctl reaches out to cluster-api's repo directly and downloads the yaml and prints it out to std out and 2) we generate all the different versions of yaml and embed them into capdctl so that capdctl doesn't need to hit the network to work.

I'm sure there are more implementations, these are just two suggestions. I'd leave this up to the implementer to pick one.

This could very well lead us into the realm of testing cluster-api v1alpha1 to v1alpha2 upgrades.

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:

This PR removes the need to copy and paste RBAC and CRD definitions. Instead we download them from a provided version of CAPI.

This PR also adds many fixes to support cluster-api v0.1.4. 

This PR adds a very annoying bug that I've yet to find a good solution for regarding kubeconfig secrets and the cluster endpoint.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #32 

```release-note
Removes `capd` and `crds` command since those were only useful for setting up a management cluster
```

### CODE REVIEW

**Comment by chuckha** [comment]
/hold

this is not right, rbac changed a fair bit here

**Comment by chuckha** [comment]
/hold cancel

yay this is finally done

File: actuators/machine.go [hunk 1]
```diff
@@ -81,14 +80,9 @@ func (m *Machine) Create(ctx context.Context, c *clusterv1.Cluster, machine *clu
 				m.Log.Error(err, "Error adding control plane")
 				return err
 			}
-			nodeUID, err := actions.GetNodeRefUID(c.GetName(), controlPlaneNode.Name())
-			if err != nil {
-				m.Log.Error(err, "Error getting node reference UID")
-				return err
-			}
-			providerID := providerID(controlPlaneNode.Name())
+			providerID := actions.ProviderID(controlPlaneNode.Name())
```
Comment (chuckha) [inline actuators/machine.go]: We no longer have to set the machine ProviderID as the node ref controller will do that for us

File: cmd/capd-manager/main.go [hunk 2]
```diff
@@ -35,6 +36,9 @@ import (
 )
 
 func main() {
+	flag.Set("v", "0")
```
Comment (chuckha) [inline cmd/capd-manager/main.go]: This may not be necessary.

File: kind/actions/cluster_actions.go [hunk 3]
```diff
@@ -379,3 +346,8 @@ func KubeadmReset(clusterName, nodeName string) error {
 
 	return nil
 }
+
+// ProviderID formats the provider id needed to set on the node
+func ProviderID(name string) string {
```
Comment (chuckha) [inline kind/actions/cluster_actions.go]: Put this logic in ONE place instead of having it split in two places with the wrong provider ID

File: kind/actions/kind.go [hunk 4]
```diff
@@ -236,13 +236,18 @@ func ListControlPlanes(clusterName string) ([]nodes.Node, error) {
 		fmt.Sprintf("label=%s=%s", constants.NodeRoleKey, constants.ControlPlaneNodeRoleValue))
 }
 
-// getLoadBalancerPort returns the port on the host on which the APIServer is exposed
-func getLoadBalancerPort(allNodes []nodes.Node) (int32, error) {
+// GetLoadBalancerHostAndPort returns the port on the host on which the APIServer is exposed
+func GetLoadBalancerHostAndPort(allNodes []nodes.Node) (string, int32, error) {
```
Comment (chuckha) [inline kind/actions/kind.go]: This gets the docker IP of the load balancer container. We use this to write the Docker IP into the kubeadm config for the node-ref controller

File: cmd/capdctl/main.go [hunk 5]
```diff
@@ -362,950 +357,76 @@ spec:
...
+			continue
+		case tar.TypeReg:
+			for _, crd := range crds {
+				// Skip the kustomization files for now. Would like to use kustomize in future
+				if strings.HasSuffix(header.Name, "kustomization.yaml") {
+					continue
+				}
+
+				// This is a poor person's kustomize
+				if strings.HasSuffix(header.Name, "manager.yaml") {
```
Comment (chuckha) [inline cmd/capdctl/main.go]: This makes me sad but it is better than copy and pasting

File: actuators/actuators.go [hunk 6]
```diff
@@ -71,6 +72,22 @@ func kubeconfigToSecret(clusterName, namespace string) (*v1.Secret, error) {
 		return nil, errors.WithStack(err)
 	}
 
+	allNodes, err := nodes.List(fmt.Sprintf("label=%s=%s", constants.ClusterLabelKey, clusterName))
+	if err != nil {
+		return nil, errors.WithStack(err)
+	}
+
+	// This is necessary so the management cluster in a container can talk to another container.
```
Comment (chuckha) [inline actuators/actuators.go]: This is the big hack.

The Management cluster, running the NodeRef controller needs to talk to the child clusters.

The management cluster and child cluster must communicate over DockerIP address/ports.

The load balancer listens on <docker_ip>:6443 and exposes a port on the host at some random open port. Any traffic directed to the nginx container will get sent over to all the control plane nodes in the cluster.

Since the NodeRef controller is running inside a container, it must reference the child cluster load balancer host by using the Docker IP address and port 6443, but us, running on the docker host, must use the localhost and random port the LB is exposing to our system.

Right now the secrets will work only for the node ref and in order for us to interact with the child clusters via kubeconfig we take the secret uploaded, rewrite the kube-apiserver-address to be 127.0.0.1:<randomport>. It's not perfect but it works to at least play with cluster-api v0.1.4

Comment (vincepri) [reply actuators/actuators.go]: I'd add this description to the code expanding the comments

File: cmd/capd-manager/main.go (hunk 2 above)
Comment (vincepri) [reply cmd/capd-manager/main.go]: +1, it can probably be removed

File: cmd/capd-manager/main.go [hunk 7]
```diff
@@ -35,6 +36,9 @@ import (
...
+	flag.Parse()
+
 	cfg, err := config.GetConfig()
 	if err != nil {
 		panic(err)
```
Comment (vincepri) [inline cmd/capd-manager/main.go]: klog.Fatal?

File: kind/actions/cluster_actions.go [hunk 8]
```diff
@@ -179,7 +179,7 @@ func KubeadmInit(clusterName, version string) error {
 	}
 
 	// save the kubeconfig on the host with the loadbalancer endpoint
-	hostPort, err := getLoadBalancerPort(allNodes)
+	_, hostPort, err := GetLoadBalancerHostAndPort(allNodes)
```
Comment (vincepri) [inline kind/actions/cluster_actions.go]: hostPort -> port?

File: actuators/actuators.go [hunk 9]
```diff
@@ -71,6 +72,22 @@ func kubeconfigToSecret(clusterName, namespace string) (*v1.Secret, error) {
...
+	// They share the same bridged network and the load balancer does respond on 6443 at its docker IP
+	// however, the *HOST* is listening on some random port (the one returned from the GetLoadBalancerHostAndPort).
+	lbip, _, err := actions.GetLoadBalancerHostAndPort(allNodes)
+	lines := bytes.Split(data, []byte("\n"))
+	for i, line := range lines {
+		if bytes.Contains(line, []byte("https://")) {
+			lines[i] = []byte(fmt.Sprintf("    server: https://%s:%d", lbip, 6443))
```
Comment (akutz) [inline actuators/actuators.go]: Hi @chuckha,

Should the port always be assumed?

File: actuators/actuators.go [hunk 10]
```diff
@@ -71,6 +72,22 @@ func kubeconfigToSecret(clusterName, namespace string) (*v1.Secret, error) {
...
+	allNodes, err := nodes.List(fmt.Sprintf("label=%s=%s", constants.ClusterLabelKey, clusterName))
+	if err != nil {
+		return nil, errors.WithStack(err)
+	}
+
+	// This is necessary so the management cluster in a container can talk to another container.
+	// They share the same bridged network and the load balancer does respond on 6443 at its docker IP
+	// however, the *HOST* is listening on some random port (the one returned from the GetLoadBalancerHostAndPort).
+	lbip, _, err := actions.GetLoadBalancerHostAndPort(allNodes)
+	lines := bytes.Split(data, []byte("\n"))
```
Comment (akutz) [inline actuators/actuators.go]: Hi @chuckha,

Why not use [`ScanLines`](https://golang.org/pkg/bufio/#ScanLines)? Even if not, maybe prefer the Golang regex `\r?\n`?

File: actuators/machine.go (hunk 1 above)
Comment (akutz) [reply actuators/machine.go]: Hi @chuckha,

I thought you're **required** to set the machine's ProviderID in order for the NodeRef controller to match the machine with the node?

File: cmd/capdctl/main.go [hunk 11]
```diff
@@ -68,12 +74,9 @@ func (mo *machineDeyploymentOptions) initFlags(fs *flag.FlagSet) {
...
 	setup := flag.NewFlagSet("setup", flag.ExitOnError)
 	managementClusterName := setup.String("cluster-name", "management", "The name of the management cluster")
-
-	// crds takes no args
-
-	capd := flag.NewFlagSet("capd", flag.ExitOnError)
-	capdImage := capd.String("capd-image", "gcr.io/kubernetes1-226021/capd-manager:latest", "The capd manager image to run")
-	capiImage := capd.String("capi-image", "gcr.io/k8s-cluster-api/cluster-api-controller:0.1.3", "The capi manager image to run")
+	version := setup.String("capi-version", "v0.1.4", "The CRD versions to pull from CAPI")
+	capdImage := setup.String("capd-image", "gcr.io/kubernetes1-226021/capd-manager:latest", "The capd manager image to run")
```
Comment (akutz) [inline cmd/capdctl/main.go]: Hi @chuckha,

I'm not personally a fan of `latest` as it has unpredictable results. Will using it here result in possible breakage?

File: kind/actions/kind.go [hunk 12]
```diff
@@ -236,13 +236,18 @@ func ListControlPlanes(clusterName string) ([]nodes.Node, error) {
...
 	if err != nil {
-		return 0, err
+		return "", 0, err
 	}
-	return node.Ports(6443)
+	ipv4, _, err := node.IP()
+	if err != nil {
+		return "", 0, err
+	}
+	port, err := node.Ports(6443)
```
Comment (akutz) [inline kind/actions/kind.go]: Hi @chuckha,

I made a note of this port elsewhere. Maybe make this a constant or configurable?

File: actuators/actuators.go (hunk 10 above)
Comment (chuckha) [reply actuators/actuators.go]: ScanLines would also work, this was just in my head at the time. If this becomes an issue in the future we can address it later.

File: actuators/actuators.go (hunk 9 above)
Comment (chuckha) [reply actuators/actuators.go]: yes, the port should always be assumed as 6443. The apiservers will always be listening on their own IP at port 6443 until we allow users to customize support. This will change when support for that feature is added.

File: kind/actions/cluster_actions.go (hunk 8 above)
Comment (chuckha) [reply kind/actions/cluster_actions.go]: maybe? I don't really see a huge benefit in this rename. I recognize host is a bit inaccurate technically but it may help to think about each container as a host.

File: kind/actions/kind.go (hunk 12 above)
Comment (chuckha) [reply kind/actions/kind.go]: That sounds like a great follow on/issue. I'll make one to track that work.

https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/66

File: kind/actions/cluster_actions.go (hunk 8 above)
Comment (chuckha) [reply kind/actions/cluster_actions.go]: ah i refer to host as docker host in other places, i will clarify, good point

File: actuators/actuators.go (hunk 10 above)
Comment (akutz) [reply actuators/actuators.go]: Fair, but I also don't think there's a good reason for **not** switching to stdlib.

File: actuators/machine.go (hunk 1 above)
Comment (chuckha) [reply actuators/machine.go]: you're right. I definitely meant that we don't have to set the machine's NodeRef. We still do have to set the provider ID

Comment (akutz) [reply actuators/machine.go]: Thank you for the clarification. For a moment I thought my understanding of this process was completely backwards :)

File: actuators/actuators.go (hunk 10 above)
Comment (chuckha) [reply actuators/actuators.go]: I don't understand what you mean, `bytes` is in the stdlib

Comment (akutz) [reply actuators/actuators.go]: Yeah, sorry, my response was poorly worded. I was referring to how `ScanLines` uses a more comprehensive matching pattern. If this won't be an issue here because the line endings are guaranteed, then this is fine.

Comment (chuckha) [reply actuators/actuators.go]: ah i see what you mean. Yes, that would definitely be more robust. It will be worth fixing if we need to fix it later as I'm not expecting line endings other than `\n` at this time. The file we're reading is generated by kubeadm on a unix based system.

File: cmd/capdctl/main.go (hunk 11 above)
Comment (chuckha) [reply cmd/capdctl/main.go]: Totally agree. I've opened an issue to figure out a better strategy here: https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/67

File: cmd/capd-manager/main.go (hunk 7 above)
Comment (chuckha) [reply cmd/capd-manager/main.go]: Yep, This is covered in https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/8

I'll time that out soon depending on if the contributor contributes or not

File: actuators/actuators.go (hunk 10 above)
Comment (akutz) [reply actuators/actuators.go]: FWIW, I know Golang treats `\n` as a special character. If you use it in a `fmt.Sprintf` (or a variant), Go will always translate `\n` to the OS-specific line-ending character(s). I'm not sure if this is the case on scanning though. Either way, as you said, it's a non-issue here.
