### PR TITLE
Cluster reconciliation should reconcile exited ELB

### LINKED ISSUE #52: Cluster actuator should reconcile deleted ELB nodes
/kind bug

**What steps did you take and what happened:**
- Setup management cluster using `capdctl setup`
- Apply capi CRDs using `capdctl crd...`
- Deploy capd controller manager using `capdctl capd ...`
- Create a sample workload cluster. cluster only w/o creating any machines
- Find the ELB for the workload cluster using `docker ps --filter name=<Cluster-Name>-external-load-balancer
- Kill the ELB container using `docker kill <ContainerID>
- Wait for the next reconciliation loop of the cluster controller and the actuator fails to detect the deleted ELB and logs
```
External Load Balancer already exists. Nothing to do for this cluster.
```

**What did you expect to happen:**
Deleted ELB should have been detected and a new ELB should have been setup. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-docker version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by ashish-amarnath**
* get only running ELB containers
* remove exited ELB containers with name conflict

Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>

**What this PR does / why we need it**:
Cluster reconciliation should reconcile deleted ELBs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #52 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
@chuckha I like the cleaning up on cluster delete. But I think we need to keep the container prune logic in `SetupLoadbalancer`
About how I am ending up w/ exited containers... I am being nasty and killing them.
Opened an issue https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/52 w/ repro

**Comment by ashish-amarnath** [comment]
@amy Yes, we should have a good testing story for capd as a whole. This scenario, in particular, is kinda hard to test via automated tests. The repro steps for this is pretty much me doing bad things on purpose.

**Comment by chuckha** [comment]
interesting...

i'd really like to find a balance here between readability and robustness.

CAPD doesn't have to be robust as it will never be a production system and should explicitly be designed to not be a robust system and more to be a general example of cluster-api assumptions.

So I'm thinking about what is the equivalent use case in cluster-api-provider-aws -- if we stop a node I don't think even CAPA is smart enough to clean up the old stopped node.

Because of that I think this logic should move into to the cluster delete and the SetupLoadBalancer should assume the environment is clean. Does that seem reasonable to you?

**Comment by ashish-amarnath** [comment]
@chuckha drawing comparison w/ capa.. this is equivalent to deleting the ELB fronting the API server. At which point, IIRC, capa controller will reconcile the deleted ELB. No?

**Comment by chuckha** [comment]
That's a good comparison, certainly more accurate than mine. There seems to be no equivalent state between aws and docker with regards to killing the container. A stopped container == what in AWS world? I would suggest that instead of cleaning up before creating that we instead add `--rm` to the load balancer set up.

The only use case this particular code is covering is adding support for the `docker kill` command when really the only delete operation we support is `docker rm (-f)`. Do you see a use case for supporting docker kill?

**Comment by ashish-amarnath** [comment]
> A stopped container == what in AWS world?
Depends on which container you stop. Stopping the `nginx` (loadbalancer) container == killing the ELB. Stopping the `kind node` container == deleting the EC2 instance. There is also a scenario where you stop the EC2 instance. In that case, capa controller will recreate it. At least based on https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/aws/services/ec2/instances.go#L107-L111 that is what I would expect.

**Comment by chuckha** [comment]
ok, I think I see the use case now. The outlined use case for this is simulating a stopped load balancer. This situation doesn't exist in AWS since you cannot stop and ELB, but it does exist in docker. Do I have it right?

**Comment by ashish-amarnath** [comment]
> The outlined use case for this is simulating a stopped load balancer. 

This is correct.

> This situation doesn't exist in AWS since you cannot stop and ELB

In AWS you can delete the ELB from the AWS console and the capa cluster actuator will recreate it.

**Comment by chuckha** [comment]
/lgtm

on amy's behalf

File: actuators/actuators.go [hunk 1]
```diff
@@ -40,9 +44,11 @@ func getRole(machine *clusterv1.Machine) string {
 }
 
 func getExternalLoadBalancerNode(clusterName string) (*nodes.Node, error) {
+	fmt.Printf("Getting external load balancer node for cluster %q\n", clusterName)
```
Comment (detiber) [inline actuators/actuators.go]: These `fmt.Printf`s should be replaced with log statements now that https://github.com/kubernetes-sigs/cluster-api-provider-docker/pull/27 has merged.

Comment (ashish-amarnath) [reply actuators/actuators.go]: #27 added loggers into the clusterActuator and machineActuators. This function is not in either of those scopes. So, we'll need to use `klog` or something like that.
Looks like the build also failed because of `undefined: fmt`

Comment (chuckha) [reply actuators/actuators.go]: the interim step is to pass a log through to all of these functions and rely on the logger interface. we should not use klog anywhere.

Comment (neolit123) [reply actuators/actuators.go]: > we should not use klog anywhere.
+1
always pass a logger interface and not the logging implementation directly, whether it's fmt or klog.

Comment (ashish-amarnath) [reply actuators/actuators.go]: fixed!

**Comment by chuckha** [comment]
/lgtm

@detiber you ok removing the hold?
