### PR TITLE
remove `kind` the binary as a dependnecy

### LINKED ISSUE #55: cluster api v0.1.4 doesn't work with current implementation
/kind bug

The main problem lies in the fact that the cluster api node ref controller, running in the management cluster (kind) doesn't share the network with the load balancer.

For this to work cluster API network must have access to the child cluster's network.

### PR DESCRIPTION
**Pull request by chuckha**
Bump the kind library dep to v0.4.0

Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:

This PR now creates the management cluster using the same functions that the actuators use to build regular control plane nodes. No more nested containers.

We need this because of node-ref. The container images that contain a kubernetes must share the same network so that node-ref controller can talk to child clusters. Without this there is no way to shove the network down into containerd land inside the kind node.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55 

**Special notes for your reviewer**:

**Release note**:
```release-note
Removes kind the binary as a dependency
```

I'm adding a hold so I can work on the README before this merges.

/hold

### CODE REVIEW

File: kind/actions/cluster_actions.go [hunk 1]
```diff
@@ -149,13 +150,23 @@ func KubeadmInit(clusterName string) error {
 	if err != nil {
 		return err
 	}
+	// Upload certs flag changed to non-experimental in >= 1.15
+	uploadCertsFlag := "--experimental-upload-certs"
+	parts := strings.Split(version, ".")
```
Comment (neolit123) [inline kind/actions/cluster_actions.go]: probably better to use ParseSemantic from api-machinery/utils/version here.

Comment (chuckha) [reply kind/actions/cluster_actions.go]: i was looking around for that lib. I knew it existed somewhere. I will use that, thank you!

**Comment by chuckha** [comment]
/hold cancel

Ready to go!

File: cmd/capdctl/main.go [hunk 2]
```diff
@@ -242,37 +248,43 @@ func machineYAML(opts *machineOptions) string {
 }
 
 func makeManagementCluster(clusterName string) {
-	kind := execer.NewClient("kind")
-	// start kind with docker mount
-	kindConfig, err := kindConfigFile()
+	fmt.Println("Creating a brand new cluster")
+	elb, err := actions.SetUpLoadBalancer(clusterName)
 	if err != nil {
 		panic(err)
```
Comment (neolit123) [inline cmd/capdctl/main.go]: out of scope of this PR, but the `panic()` pattern here is not recommended.
errors should bubble up to an exit(1).

File: kind/actions/cluster_actions.go [hunk 3]
```diff
@@ -149,13 +150,23 @@ func KubeadmInit(clusterName string) error {
 	if err != nil {
 		return err
 	}
+	// Upload certs flag changed to non-experimental in >= 1.15
+	uploadCertsFlag := "--experimental-upload-certs"
+	parsedVersion, err := k8sverison.ParseGeneric(version)
```
Comment (neolit123) [inline kind/actions/cluster_actions.go]: should be ParseSemantic? generic will fail parsing a k8s version with pre-release + metadata.

File: cmd/capdctl/main.go (hunk 2 above)
Comment (vincepri) [reply cmd/capdctl/main.go]: ...or `klog.Fatal`

Comment (chuckha) [reply cmd/capdctl/main.go]: Right now i'm keeping panic for consistency. I opened https://github.com/kubernetes-sigs/cluster-api-provider-docker/issues/8 to get a new contributor involved but will probably timeout on the issue soon since this can't live for much longer

File: kind/actions/cluster_actions.go (hunk 3 above)
Comment (chuckha) [reply kind/actions/cluster_actions.go]: that's ok, we won't be using those tags (yet). if we do end up needing it we can change it later

**Comment by chuckha** [comment]
closes #28
